"""
claude_reporter.py — Converts a BlastRadiusReport into a GitHub PR comment.

Uses Claude to produce structured, human-readable markdown with severity
indicators, affected asset tables, PII warnings, migration guidance, and
owner @mentions.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime

import anthropic

from app.engine.blast_radius import AffectedAsset, BlastRadiusReport

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Model selection
# ---------------------------------------------------------------------------

_MODEL_PROD = "claude-sonnet-4-5"
_MODEL_DEV  = "claude-haiku-4-5-20251001"

def _model() -> str:
    env = os.getenv("FLUXGUARDIAN_ENV", "dev").lower()
    return _MODEL_PROD if env == "prod" else _MODEL_DEV


# ---------------------------------------------------------------------------
# Severity helpers
# ---------------------------------------------------------------------------

_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high":     "🔴",
    "medium":   "🟠",
    "low":      "🟢",
}

_SEVERITY_LABEL: dict[str, str] = {
    "critical": "CRITICAL",
    "high":     "HIGH",
    "medium":   "MEDIUM / WARNING",
    "low":      "SAFE",
}


# ---------------------------------------------------------------------------
# Few-shot example embedded in the system prompt
# ---------------------------------------------------------------------------

_FEW_SHOT_INPUT = """\
EXAMPLE INPUT (BlastRadiusReport):
{
  "schema_change": {
    "change_type": "drop_column",
    "table": "orders",
    "old_column": "legacy_note",
    "risk": "critical"
  },
  "affected_assets": [
    {"name": "CFO Dashboard", "asset_type": "dashboard", "severity": "high",
     "owner_name": "Priya Sharma", "owner_email": "priya@acme.com",
     "slack_handle": "@priya", "reason": "Direct dependency via lineage"},
    {"name": "billing_etl", "asset_type": "pipeline", "severity": "medium",
     "owner_name": "Raj Khanna", "owner_email": "raj@acme.com",
     "slack_handle": "@raj", "reason": "Indirect dependency (depth 2)"}
  ],
  "pii_involved": false,
  "overall_severity": "high",
  "requires_governance_approval": false,
  "summary_one_line": "Dropping orders.legacy_note will impact 2 downstream assets",
  "unique_owner_emails": ["priya@acme.com", "raj@acme.com"]
}"""

_FEW_SHOT_OUTPUT = """\
EXAMPLE OUTPUT (GitHub PR comment markdown):

## 🔴 FluxGuardian — HIGH severity schema change detected

**`DROP COLUMN orders.legacy_note`**

This pull request removes the `legacy_note` column from the `orders` table.
While the column appears unused, 2 downstream assets still reference it via
lineage. The CFO Dashboard reads this column directly; the billing ETL
pipeline inherits the dependency transitively. Both consumers will break at
runtime after this migration ships.

### Affected assets

| Asset | Type | Severity | Owner |
|-------|------|----------|-------|
| CFO Dashboard | dashboard | 🔴 HIGH | @priya |
| billing_etl | pipeline | 🟠 MEDIUM | @raj |

### Safe migration plan

```sql
-- Step 1: deploy the new code that stops reading legacy_note
-- Step 2: verify no live queries reference the column (check query logs 24 h)
ALTER TABLE orders
  RENAME COLUMN legacy_note TO legacy_note_deprecated;

-- Step 3: after 1 release cycle with no errors, drop permanently
-- ALTER TABLE orders DROP COLUMN legacy_note_deprecated;
```

> **Owners to ping:** @priya @raj — please confirm no active reads before merging.

---
*🤖 Generated by [FluxGuardian](https://github.com/fluxguardian)*"""


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

def _build_prompt(report: BlastRadiusReport) -> str:
    sc   = report.schema_change
    sev  = report.overall_severity
    emoji = _SEVERITY_EMOJI.get(sev, "🟡")
    label = _SEVERITY_LABEL.get(sev, sev.upper())

    # Serialize report as clean JSON for context
    report_json = json.dumps(
        report.model_dump(mode="json"),
        indent=2,
        default=str,
    )

    # Owner @mention list for the prompt
    handles = [
        a.slack_handle or f"@{a.owner_email.split('@')[0]}"
        for a in report.affected_assets
        if a.owner_email or a.slack_handle
    ]
    unique_handles = list(dict.fromkeys(handles))  # deduplicate, preserve order

    migration_verb = {
        "drop_column":       f"DROP COLUMN {sc.table}.{sc.old_column or sc.new_column}",
        "rename_column":     f"RENAME COLUMN {sc.table}.{sc.old_column} → {sc.new_column}",
        "drop_table":        f"DROP TABLE {sc.table}",
        "alter_column_type": f"ALTER TYPE {sc.table}.{sc.old_column}  {sc.old_type} → {sc.new_type}",
        "add_column":        f"ADD COLUMN {sc.table}.{sc.new_column}",
        "rename_table":      f"RENAME TABLE {sc.table} → {sc.new_column}",
    }.get(sc.change_type, sc.change_type.replace("_", " ").upper())

    return f"""\
You are FluxGuardian, a data engineering assistant embedded in GitHub pull requests.

Your task: convert the BlastRadiusReport JSON below into a concise, professional
GitHub PR comment in markdown. The comment should be 300-500 words.

Tone: technical but friendly — a senior data engineer reviewing a colleague's PR.
Audience: engineers and data consumers who may not know all the downstream systems.
Do NOT use jargon like "BFS traversal" or "FQN". Use plain names.

REQUIRED SECTIONS (in this order):
1. Title line: `## {emoji} FluxGuardian — {label} severity schema change detected`
2. Bold subtitle: the change in plain English (e.g. **`{migration_verb}`**)
3. One-paragraph plain-English summary of the change and its impact
4. "### Affected assets" table (columns: Asset | Type | Severity | Owner)
   - Use emoji for severity: 🔴 HIGH/CRITICAL, 🟠 MEDIUM, 🟢 LOW
   - If no assets are affected, write: "✅ No downstream consumers detected."
5. "### Safe migration plan" — a 3-step SQL code block:
   - Step 1: deploy code that stops reading the old column/table
   - Step 2: a safe intermediate SQL (rename to _deprecated, or a transitional migration)
   - Step 3 (commented out): the final destructive statement after validation
6. If `pii_involved` is true: add a `> ⚠️ **PII Warning** ...` blockquote
   explaining which PII classifications are at risk and that governance approval
   is required before merging.
7. Owner ping line: `> **Owners to ping:** {" ".join(unique_handles) if unique_handles else "_(no owners found)_"}`
8. Footer (exact): `---\\n*🤖 Generated by [FluxGuardian](https://github.com/fluxguardian)*`

{_FEW_SHOT_INPUT}

{_FEW_SHOT_OUTPUT}

---

Now generate the comment for this report:

```json
{report_json}
```
"""


# ---------------------------------------------------------------------------
# ClaudeReporter
# ---------------------------------------------------------------------------

class ReporterResult:
    def __init__(self, markdown: str, tokens_used: int) -> None:
        self.markdown   = markdown
        self.tokens_used = tokens_used


class ClaudeReporter:
    """
    Converts a BlastRadiusReport into a GitHub PR comment via Claude.

    Usage:
        reporter = ClaudeReporter()
        result   = await reporter.generate(report)
        print(result.markdown)
    """

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        self._client = anthropic.Anthropic(
            api_key=api_key or os.getenv("ANTHROPIC_API_KEY"),
        )
        self._model = model or _model()

    def generate(self, report: BlastRadiusReport) -> ReporterResult:
        """Generate a markdown PR comment synchronously."""
        prompt = _build_prompt(report)
        logger.info(
            "ClaudeReporter: calling %s for %s on %s",
            self._model,
            report.schema_change.change_type,
            report.schema_change.table,
        )

        message = self._client.messages.create(
            model=self._model,
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )

        text = "".join(
            block.text for block in message.content if hasattr(block, "text")
        ).strip()

        tokens = (
            message.usage.input_tokens + message.usage.output_tokens
            if message.usage
            else 0
        )

        logger.info("ClaudeReporter: done — %d tokens used", tokens)
        return ReporterResult(markdown=text, tokens_used=tokens)

    async def agenerate(self, report: BlastRadiusReport) -> ReporterResult:
        """Async wrapper — runs generate() in a thread pool."""
        import asyncio
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self.generate, report)
